---
- name: ansible playbook to test ansible vault
  hosts: all
  become: true
  vars_files:
    - vault-pass.yml
  tasks:
   - name: Clone a repo
     git:
       repo: https://{{ token }}@github.com/Knulp86/vault.git
       dest: /opt/ansadmin/test-vault
