- name: This playbook install HTTPD
  hosts: all
  become: true 
  tasks:
  - name: install httpd package
    yum:
     name: httpd
     state: installed
    when: ansible_os_family ==  "RedHat"
    notify: start httpd service
  handlers:
  - name: start httpd service
    service:
     name: httpd
     state: started
    when: ansible_os_family ==  "RedHat"
    static: yes

  - name: install apache2
    apt:
     name: apache2
     state: present
    when: ansible_os_family ==  "Debian"
    notify: start apache2
  handlers:
  - name: start apache2
    service:
     name: apache2
     state: started
    when: ansible_os_family ==  "Debian"

  - name: copy index.html
    copy:
      src: /opt/ansible/index.html
      dest: /var/www/html
      mode: 0666
